image: node:12

variables:
    CARGO_HOME: "$CI_PROJECT_DIR/.cargo"
    RUSTUP_HOME: "$CI_PROJECT_DIR/.rustup"

cache:
  paths:
    - node_modules/
    - tests/node_modules/
    - tests/nearcore/
    - bindings/node_modules/
    - .cargo/
    - tests/out/

stages:
  - install
  - build
  - test

install_dependencies:
  stage: install
  script:
    - yarn && cd bindings && yarn

install_test_dependencies:
  stage: install
  script:
    - cd tests && yarn && cd ../bindings/tests && npm install

build_bindings: 
  stage: build
  script:
    - cd bindings && npm run build

build_test_wasm:
  stage: build
  script:
    - cd tests && yarn build

build_near_vm_runner_standalone:
  stage: build
  script:
    - export PATH="$PATH:$CARGO_HOME/bin"
    - cd tests && ./build-near-vm-runner-standalone.sh

run_bindings_tests:
  stage: test
  script:
    - cd bindings/tests && yarn test

run_aspect_tests:
  stage: test
  script:
    - cd tests && yarn test

run_assembly_test:
  stage: test
  script:
    - cd tests && ./test.sh
